<?php
include_once("conexion.php");
$busqueda = $_POST['busqueda'];
$busqueda = '%'.$busqueda.'%';
$busquery = "SELECT titulo, tipo, imagen, descripcion, nom_usuario, telefono FROM prenda INNER JOIN usuario WHERE tipo LIKE '$busqueda' OR descripcion LIKE '$busqueda' OR titulo LIKE '$busqueda' AND prenda.id_usuario = usuario.id_usuario LIMIT 6;";
$resultado = mysqli_query($conexion, $busquery);
$resArray = mysqli_fetch_assoc($resultado);
$_SESSION['resTitulo'] = $resArray['titulo'];
$_SESSION['resTipo'] = $resArray['tipo'];
$_SESSION['resImagen'] = $resArray['imagen'];
$_SESSION['resDescripcion'] = $resArray['descripcion'];
$_SESSION['resUsuario'] = $resArray['nom_usuario'];
$_SESSION ['busqueda'] = $busqueda;
$_SESSION['telefono'] = $resArray['telefono'];
$resArray = mysqli_fetch_assoc($resultado);
$_SESSION['resTitulo1'] = $resArray['titulo'];
$_SESSION['resTipo1'] = $resArray['tipo'];
$_SESSION['resImagen1'] = $resArray['imagen'];
$_SESSION['resDescripcion1'] = $resArray['descripcion'];
$_SESSION['resUsuario1'] = $resArray['nom_usuario'];
$_SESSION['telefono1'] = $resArray['telefono'];
$resArray = mysqli_fetch_assoc($resultado);
$_SESSION['resTitulo2'] = $resArray['titulo'];
$_SESSION['resTipo2'] = $resArray['tipo'];
$_SESSION['resImagen2'] = $resArray['imagen'];
$_SESSION['resDescripcion2'] = $resArray['descripcion'];
$_SESSION['resUsuario2'] = $resArray['nom_usuario'];
$_SESSION['telefono2'] = $resArray['telefono'];
$resArray = mysqli_fetch_assoc($resultado);
$_SESSION['resTitulo3'] = $resArray['titulo'];
$_SESSION['resTipo3'] = $resArray['tipo'];
$_SESSION['resImagen3'] = $resArray['imagen'];
$_SESSION['resDescripcion3'] = $resArray['descripcion'];
$_SESSION['resUsuario3'] = $resArray['nom_usuario'];
$_SESSION['telefono3'] = $resArray['telefono'];
$resArray = mysqli_fetch_assoc($resultado);
$_SESSION['resTitulo4'] = $resArray['titulo'];
$_SESSION['resTipo4'] = $resArray['tipo'];
$_SESSION['resImagen4'] = $resArray['imagen'];
$_SESSION['resDescripcion4'] = $resArray['descripcion'];
$_SESSION['resUsuario4'] = $resArray['nom_usuario'];
$_SESSION['telefono4'] = $resArray['telefono'];
$resArray = mysqli_fetch_assoc($resultado);
$_SESSION['resTitulo5'] = $resArray['titulo'];
$_SESSION['resTipo5'] = $resArray['tipo'];
$_SESSION['resImagen5'] = $resArray['imagen'];
$_SESSION['resDescripcion5'] = $resArray['descripcion'];
$_SESSION['resUsuario5'] = $resArray['nom_usuario'];
$_SESSION['telefono5'] = $resArray['telefono'];
echo "<script type='text/javascript'>
window.location.href='resultBusqueda.php';
</script>"; 
?>